version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - gocritic
    - misspell
    - prealloc
    - unconvert
    - unparam
  settings:
    govet:
      enable-all: true
      disable:
        - fieldalignment
        - shadow
    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
    misspell:
      locale: US

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/utafrali/EcommerceGo

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gocritic
        - unparam
  max-issues-per-linter: 50
  max-same-issues: 5
